#
# autogenerated with sqlacodegen
#
from sqlalchemy import BigInteger, Boolean, Column, Date, Integer, MetaData, SmallInteger, String, Table, text
from sqlalchemy.dialects.postgresql.base import CIDR
from sqlalchemy import create_engine, MetaData

metadata = MetaData()

t_bla = Table(
    'bla', metadata,
    Column('count', BigInteger),
    Column('usr', String)
)


t_confirm = Table(
    'confirm', metadata,
    Column('id', Integer, nullable=False, server_default=text("nextval('confirm_id_seq'::regclass)")),
    Column('usr_id', Integer),
    Column('type', SmallInteger),
    Column('key', String),
    Column('send', Integer, server_default=text("trunc(date_part('epoch'::text, now()))"))
)


t_confirm_type = Table(
    'confirm_type', metadata,
    Column('id', Integer, nullable=False, server_default=text("nextval('confirm_type_id_seq'::regclass)")),
    Column('name', String(50)),
    Column('gueltig', Integer),
    Column('subject', String(80)),
    Column('mail_text', String),
    Column('ok_text', String)
)


t_confirm_type_back = Table(
    'confirm_type_back', metadata,
    Column('id', Integer),
    Column('name', String(50)),
    Column('gueltig', Integer),
    Column('subject', String(80)),
    Column('mail_text', String),
    Column('ok_text', String)
)


t_deletet_ip = Table(
    'deletet_ip', metadata,
    Column('id', Integer),
    Column('ip', CIDR),
    Column('user_id', Integer),
    Column('mac', String(80)),
    Column('description', String),
    Column('hardware', String),
    Column('place', String),
    Column('plz', String),
    Column('mobil', Boolean)
)


t_foo = Table(
    'foo', metadata,
    Column('count', BigInteger),
    Column('ip', String)
)


t_ip = Table(
    'ip', metadata,
    Column('id', Integer, nullable=False, server_default=text("nextval('ip_id_seq'::regclass)")),
    Column('ip', CIDR, unique=True),
    Column('user_id', Integer),
    Column('mac', String(80)),
    Column('description', String),
    Column('hardware', String),
    Column('place', String),
    Column('plz', String),
    Column('mobil', Boolean)
)


t_ip_back = Table(
    'ip_back', metadata,
    Column('id', Integer),
    Column('ip', CIDR),
    Column('user_id', Integer),
    Column('mac', String(80)),
    Column('description', String),
    Column('hardware', String),
    Column('place', String),
    Column('plz', String),
    Column('mobil', Boolean)
)


t_ip_export = Table(
    'ip_export', metadata,
    Column('ip_id', Integer),
    Column('ip', String, unique=True),
    Column('user_id', Integer),
    Column('mac', String),
    Column('hardware', String),
    Column('description', String),
    Column('place', String),
    Column('plz', String),
    Column('mobil', Boolean)
)


t_ip_export_back = Table(
    'ip_export_back', metadata,
    Column('ip_id', Integer),
    Column('ip', String),
    Column('user_id', Integer),
    Column('mac', String),
    Column('hardware', String),
    Column('description', String),
    Column('place', String),
    Column('plz', String),
    Column('mobil', Boolean)
)


t_p_text = Table(
    'p_text', metadata,
    Column('id', Integer, nullable=False, server_default=text("nextval('p_text_id_seq'::regclass)")),
    Column('name', String(50)),
    Column('text', String)
)


t_usr = Table(
    'usr', metadata,
    Column('id', Integer, nullable=False, server_default=text("nextval('usr_id_seq'::regclass)")),
    Column('usr', String(50), unique=True),
    Column('name', String(50)),
    Column('mail', String(50), unique=True),
    Column('pw', String(100)),
    Column('level', SmallInteger, server_default=text("4")),
    Column('status', SmallInteger, server_default=text("2")),
    Column('create_d', Date, server_default=text("now()"))
)


t_usr_back = Table(
    'usr_back', metadata,
    Column('id', Integer),
    Column('usr', String(50)),
    Column('name', String(50)),
    Column('mail', String(50)),
    Column('pw', String(100)),
    Column('level', SmallInteger),
    Column('status', SmallInteger),
    Column('create_d', Date)
)


t_usr_export = Table(
    'usr_export', metadata,
    Column('id', Integer),
    Column('name', String),
    Column('usr', String),
    Column('mail', String),
    Column('pw', String),
    Column('a', String),
    Column('b', String),
    Column('c', String),
    Column('d', String),
    Column('since', Date),
    Column('last', String),
    Column('e', String),
    Column('f', String)
)
